// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puoqbcpopsdslietfywm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1b3FiY3BvcHNkc2xpZXRmeXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxNjIwNTMsImV4cCI6MjA0OTczODA1M30.d37MBqPMpeF6--3IHbvqm0BSsG2-KKDUrkR3wPbQFe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);